FROM docker.io/indexyz/openwrt-build-env:legacy

RUN useradd \
    --create-home \
    --shell=/bin/bash \
    --uid=1000 \
    --user-group coder && \
    echo "coder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/nopasswd

USER coder