FROM codercom/enterprise-base:ubuntu

# Run everything as root
USER root

RUN apt-get update -y && \
    apt-get install nano -y

RUN apt-get update -y

# Install go
RUN curl -L "https://go.dev/dl/go1.25.0.linux-amd64.tar.gz" | tar -C /usr/local -xzvf -

# Setup go env vars
ENV GOROOT=/usr/local/go
ENV PATH=$PATH:$GOROOT/bin

ENV GOPATH=/home/coder/go
ENV GOBIN=$GOPATH/bin
ENV PATH=$PATH:$GOBIN

# Install GH cli
RUN (type -p wget >/dev/null || (sudo apt update && sudo apt install wget -y)) \
	&& sudo mkdir -p -m 755 /etc/apt/keyrings \
	&& out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
	&& cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
	&& sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
	&& sudo mkdir -p -m 755 /etc/apt/sources.list.d \
	&& echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
	&& sudo apt update \
	&& sudo apt install gh -y

# Install whichever Node version is LTS
RUN curl -sL https://deb.nodesource.com/setup_lts.x | bash -
RUN DEBIAN_FRONTEND="noninteractive" apt-get update -y && \
    apt-get install -y nodejs

# Install Yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN DEBIAN_FRONTEND="noninteractive" apt-get update && apt-get install -y yarn

# Install pnpm
RUN npm install --global corepack@latest && \
    corepack enable pnpm

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Install codex
RUN npm install -g @openai/codex

# Install claude code
RUN npm install -g @anthropic-ai/claude-code

# Install lefthook
RUN go install github.com/evilmartians/lefthook@latest

# Install goimports
RUN go install golang.org/x/tools/cmd/goimports@latest

# Install ETCD
ENV ETCD_VER=3.6.5

RUN curl -L https://github.com/etcd-io/etcd/releases/download/v${ETCD_VER}/etcd-v${ETCD_VER}-linux-amd64.tar.gz -o /tmp/etcd.tgz && \
    tar xzvf /tmp/etcd.tgz -C /tmp --strip-components=1 --no-same-owner && \
    mv /tmp/etcd /usr/local/bin && \
    mv /tmp/etcdctl /usr/local/bin && \
    mv /tmp/etcdutl /usr/local/bin && \
    rm -f /tmp/etcd.tgz

# Install kubectl
RUN curl -L "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/bin/kubectl && \
    chmod +x /usr/bin/kubectl

# kustomize
RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash -s -- /usr/local/bin

# kubebuilder
RUN  curl -L -o kubebuilder "https://go.kubebuilder.io/dl/latest/$(go env GOOS)/$(go env GOARCH)" && \
    chmod +x kubebuilder && mv kubebuilder /usr/local/bin/

# Install golangci-lint
RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | bash

# Install nix
RUN curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install linux \
  --extra-conf "system-features = kvm" \
  --init none \
  --no-confirm \
  --determinate

ENV PATH="${PATH}:/nix/var/nix/profiles/default/bin"

# Install nixd
RUN nix profile add github:nix-community/nixd
RUN nix profile add github:nixos/nixpkgs#just

# Set back to coder user
USER coder
