FROM docker.io/indexyz/openwrt-build-env:legacy

RUN /bin/bash -c useradd coder \
    --create-home \
    --shell=/bin/bash \
    --groups=docker \ 
    --uid=1000 \
    --user-group && \
    echo "coder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/nopasswd

USER coder